
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */

package com.mycompany.st10466857;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.*;

/**
 *
 * @author lab_services_student
 */

//Testing was generated by NetBeans (Apache NetBeans, 2024).

public class SeriesTest {

    private Series series;
    private List<SeriesModel> seriesList;

    @BeforeEach
    void setUp() {
        series = new Series();
        seriesList = new ArrayList<>();
    }

    private Scanner scannerFrom(String text) {
        return new Scanner(new ByteArrayInputStream(text.getBytes(StandardCharsets.UTF_8)));
    }

    private String captureStdout(Runnable action) {
        PrintStream original = System.out;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        System.setOut(new PrintStream(baos));
        try {
            action.run();
        } finally {
            System.setOut(original);
        }
        return baos.toString(StandardCharsets.UTF_8);
    }
    
    //Determine that the correct series data has been returned.
    @Test
    void TestSearchSeries() {
        seriesList.add(new SeriesModel("101", "Extreme Sports", "12", "10"));

        String out = captureStdout(() ->
            series.SearchSeries(seriesList, scannerFrom("101\n\n"))
        );

        String norm = out.toUpperCase(); //make checks case-insensitive
        assertTrue(norm.contains("SERIES FOUND"));
        assertTrue(norm.contains("SERIES ID") && norm.contains("101"));
        assertTrue(norm.contains("SERIES NAME") && norm.contains("EXTREME SPORTS")); //(BrowserStack, n.d.)
    }

    //Determine that no series was found.
    @Test
    void TestSearchSeries_SeriesNotFound() {
        String out = captureStdout(() ->
                series.SearchSeries(seriesList, scannerFrom("999\n\n"))
        );
        assertTrue(out.contains("No series data could be found for ID: 999"));
    }

    //Determine that the series has been successfully updated.
    @Test
    void TestUpdateSeries() {
        seriesList.add(new SeriesModel("101", "Extreme Sports", "12", "10"));
        // id, keep name, new age=15, keep episodes, press-enter to continue
        String input = "101\n\n15\n\n\n";

        series.UpdateSeries(seriesList, scannerFrom(input));

        assertEquals("15", seriesList.get(0).SeriesAge);
        assertEquals("Extreme Sports", seriesList.get(0).SeriesName);
        assertEquals("10", seriesList.get(0).SeriesNumberOfEpisodes); //(BrowserStack, n.d.)
    }

    //Determine that the series has been successfully deleted.
    @Test
    void TestDeleteSeries() {
        seriesList.add(new SeriesModel("101", "Extreme Sports", "12", "10"));
        String input = "101\nY\n\n";

        series.DeleteSeries(seriesList, scannerFrom(input));

        assertEquals(0, seriesList.size()); //(BrowserStack, n.d.)
    }

    //Determine that the series has not been deleted when id is incorrect.
    @Test
    void TestDeleteSeries_SeriesNotFound() {
        seriesList.add(new SeriesModel("101", "Extreme Sports", "12", "10"));
        String input = "999\n\n";

        series.DeleteSeries(seriesList, scannerFrom(input));

        assertEquals(1, seriesList.size());
        assertEquals("101", seriesList.get(0).SeriesId); //(BrowserStack, n.d.)
    }

    //Determine that a valid age restriction is accepted.
    @Test
    void TestSeriesAgeRestriction_AgeValid() {
        // Use CaptureSeries to validate input acceptance
        String input = "201\nBargain Hunters\n10\n10\n\n";
        series.CaptureSeries(seriesList, scannerFrom(input));

        assertEquals(1, seriesList.size());
        assertEquals("10", seriesList.get(0).SeriesAge); //(BrowserStack, n.d.)
    }

    //Determine that an invalid age restriction is rejected (age unchanged).
    @Test
    void TestSeriesAgeRestriction_SeriesAgeInValid() {
        seriesList.add(new SeriesModel("301", "Home Cooking", "12", "20"));
        String input = "301\n\n1\n\n\n\n";

        String out = captureStdout(() ->
                series.UpdateSeries(seriesList, scannerFrom(input))
        );

        assertEquals("12", seriesList.get(0).SeriesAge);
        assertTrue(out.contains("Invalid")); //(BrowserStack, n.d.)
    }
}

/*
Refrence list
Apache NetBeans. (2024) NetBeans IDE 24 Documentation. Available at: https://netbeans.apache.org/kb/docs/ (Accessed: 4 September 2025).
BrowserStack. n.d. JUnit and automation testing. Available at: https://www.browserstack.com/guide/junit-and-automation-testing [Accessed 4 September 2025].
Independent Institute of Education. (n.d.) [Title of the module or lesson]. Available at: https://mystudies.iie.edu.za/d2l/le/lessons/40467/topics/3551774 (Accessed: 4 September 2025).
*/