/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */
package com.mycompany.djapp;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

//Testing was generated by NetBeans (Apache NetBeans, 2024).

/**
 *
 * @author lab_services_student
 */

public class ManagerTest {

    private Manager manager;

    @BeforeEach
    void setUp() {
        manager = new Manager();
        manager.captureEquipment(new Equipment("E01", "Pioneer DJM Mixer", 54999.99, 3));
        manager.captureEquipment(new Equipment("E02", "Pioneer CDJ Player", 39999.50, 5));
        manager.captureEquipment(new Equipment("E03", "JBL Speaker", 15499.00, 7)); //(BrowserStack, n.d.)
    }

    @Test
    void testCaptureAndSearch_Found() {
        Equipment added = new Equipment("E10", "Numark Mixtrack Pro FX", 5999.00, 10);
        manager.captureEquipment(added); //(BrowserStack, n.d.)

        Equipment found = manager.searchEquipment("E10");
        assertNotNull(found, "Expected to find E10 after capture");
        assertEquals("Numark Mixtrack Pro FX", found.getEquipmentName());
        assertEquals(5999.00, found.getPrice());
        assertEquals(10, found.getStock()); //(BrowserStack, n.d.)
    }

    @Test
    void testSearch_NotFound() {
        Equipment missing = manager.searchEquipment("NOPE");
        assertNull(missing, "Expected null for non-existent ID"); //(BrowserStack, n.d.)
    }

    @Test
    void testUpdate_Success() {
        boolean updated = manager.updateEquipment("E02", "Pioneer CDJ (Updated)", 41999.99, 4);
        assertTrue(updated, "Update should return true for existing ID"); //(BrowserStack, n.d.)

        Equipment updatedEq = manager.searchEquipment("E02");
        assertNotNull(updatedEq, "Updated equipment must still exist");
        assertEquals("Pioneer CDJ (Updated)", updatedEq.getEquipmentName());
        assertEquals(41999.99, updatedEq.getPrice());
        assertEquals(4, updatedEq.getStock()); //(BrowserStack, n.d.)
    }

    @Test
    void testUpdate_NotFound() {
        boolean updated = manager.updateEquipment("BAD_ID", "X", 1.0, 1);
        assertFalse(updated, "Update should return false for non-existent ID"); //(BrowserStack, n.d.)
    }

    @Test
    void testDelete_Success() {
        boolean deleted = manager.deleteEquipment("E03");
        assertTrue(deleted, "Delete should return true for existing ID"); //(BrowserStack, n.d.)

        Equipment afterDelete = manager.searchEquipment("E03");
        assertNull(afterDelete, "Deleted item should not be searchable"); //(BrowserStack, n.d.)
    }

    @Test
    void testDelete_NotFound() {
        boolean deleted = manager.deleteEquipment("ZZZ");
        assertFalse(deleted, "Delete should return false for non-existent ID"); //(BrowserStack, n.d.)
    }

    @Test
    void testReport_Content() {
        String report = manager.generateReport();
        assertNotNull(report);
        assertTrue(report.contains("E01"));
        assertTrue(report.contains("E02"));
        assertTrue(report.contains("E03")); //(BrowserStack, n.d.)
    }
}

/*
Refrence list
Apache NetBeans. (2024) NetBeans IDE 24 Documentation. Available at: https://netbeans.apache.org/kb/docs/ (Accessed: 4 September 2025).
BrowserStack. n.d. JUnit and automation testing. Available at: https://www.browserstack.com/guide/junit-and-automation-testing [Accessed 4 September 2025].
Independent Institute of Education. (n.d.) [Title of the module or lesson]. Available at: https://mystudies.iie.edu.za/d2l/le/lessons/40467/topics/3551774 (Accessed: 4 September 2025).
*/